### PR TITLE
Make brushfire buildable in both 2.10 and 2.11

### PR DESCRIPTION
**Pull request by colinmarc**
r? @avibryant

### CODE REVIEW

**Comment by avibryant** [comment]
So how does one do a 2.10 build with this?

**Comment by colinmarc** [comment]
You have to specify `scala.version` and `scala.binary.version`. So for example:

`mvn -Dscala.version=2.10.4 -Dscala.binary.version=2.10 clean package`

**Comment by colinmarc** [comment]
This builds (and deploys) `brushfire-core` and `brushfire-scalding` just fine, but not `brushfire-finatra`, because there's no finatra for 2.11: https://github.com/twitter/finatra/pull/185

**Comment by avibryant** [comment]
Ok so let's have it default to 2.10 then so it all builds, then we can have a somewhat more manual process to get the 2.11 artifacts?

**Comment by colinmarc** [comment]
Makes sense. The build works now.

**Pull request merged**
